In [1]:
from voc import collector as co

snapshot = co.get_dataset()
print(snapshot.info)
display(snapshot.data.head())

{'artifact_id': '882e1575-e782-458c-8520-8647087a7677', 'content_sha256': '4ab823626ea458d0a2b28484bb5905906115556dd01a0d74413daea5999f0b22', 'counts_by_platform': {'app_store': 5154, 'google_play': 65100, 'x': 6553, 'youtube': 1328}, 'mlflow_run_id': 'dfe346c0969f4cf5bd373e6f15d92474', 'project_identity': 'ba6f660c892339273ac09a19bd55dced07e06de64d64cb682fd25d100c476b92', 'raw_revision_id': '5816db5a-18a8-44fc-b9a9-3314475921e2', 'raw_store_id': '/data/raw/raw.db', 'row_count': 78135, 'rules': {'blank_text': 'exclude_and_report', 'columns': ['record_id', 'platform', 'app_id', 'country', 'text', 'title', 'model_text', 'text_hash', 'rating', 'record_date', 'date_basis', 'date_precision', 'date_timezone', 'language', 'language_basis', 'relevance', 'preferred_provider', 'identity_basis'], 'combine_title_body': False, 'language_filter': None, 'platforms': ['app_store', 'google_play', 'x', 'youtube'], 'relevance_filter': None}, 'run_id': '848a615b-7e10-40af-926d-3ef9b82498e1', 'schema_version': 'workable-v1'}

,record_id,platform,app_id,country,text,title,model_text,text_hash,rating,record_date,date_basis,date_precision,date_timezone,language,language_basis,relevance,preferred_provider,identity_basis
0,appbot:498483038:3606491475,app_store,498483038,MX,Quiero ver mis movimientos y no me deja regres...,Errores en la app para ver movimientos,Quiero ver mis movimientos y no me deja regres...,d5a838f3cbc3912516bdf5832d02e7cc51e09c8e7f2d0f...,2,2025-09-01,provider_published_at,day,unknown,es,provider language field,app_target_match,appbot,provider_identity
1,appbot:498483038:3606491476,app_store,498483038,MX,"No me permite ver mis movimientos, está descon...",Mala aplicación,"No me permite ver mis movimientos, está descon...",7c2f6c168877f40be7f0a66e5666a3468e8c97710b53af...,2,2025-09-01,provider_published_at,day,unknown,es,provider language field,app_target_match,appbot,provider_identity
2,appbot:498483038:3606491477,app_store,498483038,MX,Todo bien,Recomendable,Todo bien,a53bc6df3058125dade7dd8f07ed6f1a5fd378634b10c2...,5,2025-09-01,provider_published_at,day,unknown,es,provider language field,app_target_match,appbot,provider_identity
3,appbot:498483038:3606711369,app_store,498483038,MX,La app esta muy bien solo tiene un detalle neg...,Bloqueo temporal de tarjeta de débito,La app esta muy bien solo tiene un detalle neg...,188f16374700a7dcaf98bb0466263fa5c51c689c6089d6...,4,2025-09-01,provider_published_at,day,unknown,es,provider language field,app_target_match,appbot,provider_identity
4,appbot:498483038:3606711370,app_store,498483038,MX,Con sus actualizaciones ha quedado una aplicac...,Calificación,Con sus actualizaciones ha quedado una aplicac...,63c0ca491e55ae2f1acb760b03f7f67bece3436fc176b0...,5,2025-09-01,provider_published_at,day,unknown,es,provider language field,app_target_match,appbot,provider_identity

In [1]:
from voc import collector as co

snapshot = co.get_dataset(source="s3")
release_id = snapshot.info["release_id"]

raw = co.get_dataset(
    source="s3", stage="raw", version=release_id
)
pinned = co.get_dataset(source="s3", version=release_id)

assert pinned.data.equals(snapshot.data)
assert raw.info["raw_revision_id"] == snapshot.info["raw_revision_id"]

print("Release:", release_id)
print("Raw:", raw.data.shape)
print("Workable:", snapshot.data.shape)
display(snapshot.data.head())

Release: 41e10f26-0864-421e-8c5d-c7bbf309d113
Raw: (78135, 122)
Workable: (78135, 18)

,record_id,platform,app_id,country,text,title,model_text,text_hash,rating,record_date,date_basis,date_precision,date_timezone,language,language_basis,relevance,preferred_provider,identity_basis
0,appbot:498483038:3606491475,app_store,498483038,MX,Quiero ver mis movimientos y no me deja regres...,Errores en la app para ver movimientos,Quiero ver mis movimientos y no me deja regres...,d5a838f3cbc3912516bdf5832d02e7cc51e09c8e7f2d0f...,2,2025-09-01,provider_published_at,day,unknown,es,provider language field,app_target_match,appbot,provider_identity
1,appbot:498483038:3606491476,app_store,498483038,MX,"No me permite ver mis movimientos, está descon...",Mala aplicación,"No me permite ver mis movimientos, está descon...",7c2f6c168877f40be7f0a66e5666a3468e8c97710b53af...,2,2025-09-01,provider_published_at,day,unknown,es,provider language field,app_target_match,appbot,provider_identity
2,appbot:498483038:3606491477,app_store,498483038,MX,Todo bien,Recomendable,Todo bien,a53bc6df3058125dade7dd8f07ed6f1a5fd378634b10c2...,5,2025-09-01,provider_published_at,day,unknown,es,provider language field,app_target_match,appbot,provider_identity
3,appbot:498483038:3606711369,app_store,498483038,MX,La app esta muy bien solo tiene un detalle neg...,Bloqueo temporal de tarjeta de débito,La app esta muy bien solo tiene un detalle neg...,188f16374700a7dcaf98bb0466263fa5c51c689c6089d6...,4,2025-09-01,provider_published_at,day,unknown,es,provider language field,app_target_match,appbot,provider_identity
4,appbot:498483038:3606711370,app_store,498483038,MX,Con sus actualizaciones ha quedado una aplicac...,Calificación,Con sus actualizaciones ha quedado una aplicac...,63c0ca491e55ae2f1acb760b03f7f67bece3436fc176b0...,5,2025-09-01,provider_published_at,day,unknown,es,provider language field,app_target_match,appbot,provider_identity

In [1]:
from voc import collector as co

snapshot = co.get_dataset()  # No explicit source
assert snapshot.info["source"] == "s3"
assert snapshot.info["release_id"] == "41e10f26-0864-421e-8c5d-c7bbf309d113"
print(snapshot.data.shape)

(78135, 18)